/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class statr_stat598bd_LogisticRidgeNative */

#ifndef _Included_statr_stat598bd_LogisticRidgeNative
#define _Included_statr_stat598bd_LogisticRidgeNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     statr_stat598bd_LogisticRidgeNative
 * Method:    logistic_ridge
 * Signature: ([DII[DD[DIDD[I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_statr_stat598bd_LogisticRidgeNative_logistic_1ridge
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jdoubleArray, jdouble, jdoubleArray, jint, jdouble, jdouble, jintArray);

#ifdef __cplusplus
}
#endif
#endif
