/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class statr_stat598bd_LogisticRidgeNewtonNative */

#ifndef _Included_statr_stat598bd_LogisticRidgeNewtonNative
#define _Included_statr_stat598bd_LogisticRidgeNewtonNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     statr_stat598bd_LogisticRidgeNewtonNative
 * Method:    logistic_ridge_newton
 * Signature: ([DII[DD[DIDD[I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_statr_stat598bd_LogisticRidgeNewtonNative_logistic_1ridge_1newton
  (JNIEnv *, jobject, jdoubleArray, jint, jint, jdoubleArray, jdouble, jdoubleArray, jint, jdouble, jdouble, jintArray);

#ifdef __cplusplus
}
#endif
#endif
